api_version: aster.dev/v1alpha1
kind: Package

metadata:
  name: aster-runtime
  version: 0.1.0-dev
  license: Apache-2.0

spec:
  build:
    system: cmake
  exports:
    libraries:
      - name: aster::runtime
        portable: true
  dependencies: []
