api_version: aster.dev/v1alpha2
kind: Package

metadata:
  name: asterctrl
  version: 0.2.0-alpha.1
  license: Apache-2.0

spec:
  build:
    system: cmake
    target: aster_core
  exports:
    tools:
      - aster
    transports:
      - local
      - can
      - socketcan
      - usb_cdc_acm
  dependencies: {}
