"""Deterministic files emitted from a validated DeploymentPlan."""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

import yaml

from xrobot_tools.deployment import DeploymentError, DeploymentPlan, Route
from xrobot_tools.validation import validate_document


def _write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def _yaml(document: Any) -> str:
    return yaml.safe_dump(
        document,
        sort_keys=False,
        allow_unicode=False,
        default_flow_style=False,
    )


def _json(document: Any) -> str:
    return json.dumps(document, indent=2, sort_keys=True) + "\n"


def _allocate_ids(
    names: list[str], existing: dict[str, int], minimum: int, maximum: int
) -> dict[str, int]:
    assigned = {
        name: value
        for name, value in existing.items()
        if name in names and minimum <= value <= maximum
    }
    used = set(assigned.values())
    candidate = minimum
    for name in sorted(names):
        if name in assigned:
            continue
        while candidate in used:
            candidate += 1
        if candidate > maximum:
            raise DeploymentError(f"cannot allocate ID for {name!r}; limit is {maximum}")
        assigned[name] = candidate
        used.add(candidate)
    return dict(sorted(assigned.items()))


def _load_existing_lock(path: Path, deployment_name: str) -> dict[str, Any]:
    if not path.is_file():
        return {}
    lock = validate_document(path)
    if lock["metadata"]["deployment"] != deployment_name:
        raise DeploymentError(
            f"{path}: lock belongs to deployment "
            f"{lock['metadata']['deployment']!r}, expected {deployment_name!r}"
        )
    return lock


def _route_document(route: Route, route_id: int) -> dict[str, Any]:
    return {
        "id": route_id,
        "name": route.name,
        "kind": route.kind,
        "type": route.type_name,
        "type_hash": route.type_hash,
        "source_node": route.source_node,
        "destination_nodes": list(route.destination_nodes),
        "link": route.link,
        "qos": route.qos,
        "max_rate_hz": route.max_rate_hz,
        "max_serialized_size": route.max_serialized_size,
        "max_wire_payload_size": route.max_wire_payload_size,
        "frame_count": route.frame_count,
        "bits_per_message": route.bits_per_message,
    }


def _node_header(
    plan: DeploymentPlan,
    node_name: str,
    node_id: int,
    route_ids: dict[str, int],
) -> str:
    routes = [
        route
        for route in plan.routes
        if route.source_node == node_name or node_name in route.destination_nodes
    ]
    namespace = f"xrobot::generated::{node_name}"
    entries = []
    for route in routes:
        direction = "true" if route.source_node == node_name else "false"
        entries.append(
            "    GeneratedRoute{"
            f"{route_ids[route.name]}, \"{route.name}\", \"{route.type_name}\", "
            f"{direction}, {route.max_serialized_size}, "
            f"{route.max_wire_payload_size}, {route.frame_count}"
            "},"
        )
    route_lines = "\n".join(entries)
    return f"""\
#pragma once

#include <array>
#include <cstddef>
#include <cstdint>
#include <string_view>

// Generated by xrctl. Do not edit.
namespace {namespace} {{

struct GeneratedRoute {{
  std::uint16_t id;
  std::string_view name;
  std::string_view type;
  bool publishes;
  std::size_t max_serialized_size;
  std::size_t max_wire_payload_size;
  std::uint8_t frame_count;
}};

inline constexpr std::uint8_t kNodeId = {node_id};
inline constexpr std::string_view kNodeName = "{node_name}";
inline constexpr std::string_view kDeploymentHash = "{plan.deployment_hash}";
inline constexpr std::string_view kSchemaHash = "{plan.schema_hash}";
inline constexpr std::array<GeneratedRoute, {len(routes)}> kRoutes{{{{
{route_lines}
}}}};

}}  // namespace {namespace}
"""


def _node_main(node_name: str) -> str:
    namespace = f"xrobot::generated::{node_name}"
    return f"""\
#include "node_config.hpp"

// Generated composition entry. Module construction is emitted beside this file.
namespace {namespace} {{

int GeneratedMain() noexcept {{
  static_assert(kNodeId != 0);
  return 0;
}}

}}  // namespace {namespace}
"""


def _executor_report(plan: DeploymentPlan) -> dict[str, Any]:
    nodes: dict[str, list[dict[str, Any]]] = {
        name: [] for name in plan.deployment["nodes"]
    }
    for instance in plan.instances:
        for executor in instance.manifest.document["spec"]["executors"]:
            nodes[instance.node].append(
                {
                    "name": f"{instance.name}__{executor['name']}",
                    "instance": instance.name,
                    **executor,
                }
            )
    for executors in nodes.values():
        executors.sort(key=lambda item: item["name"])
    return {"nodes": nodes}


def _memory_report(plan: DeploymentPlan) -> dict[str, Any]:
    nodes: dict[str, Any] = {}
    for node_name in sorted(plan.deployment["nodes"]):
        node_instances = [item for item in plan.instances if item.node == node_name]
        executors = [
            executor
            for instance in node_instances
            for executor in instance.manifest.document["spec"]["executors"]
        ]
        node_routes = [
            route
            for route in plan.routes
            if route.source_node == node_name or node_name in route.destination_nodes
        ]
        queue_slots = sum(int(item["queue_depth"]) for item in executors)
        nodes[node_name] = {
            "module_instances": len(node_instances),
            "executor_count": len(executors),
            "executor_stack_bytes": sum(int(item["stack_bytes"]) for item in executors),
            "executor_queue_slots": queue_slots,
            "executor_queue_bytes_estimate": queue_slots * 8,
            "route_count": len(node_routes),
            "route_buffer_bytes_minimum": sum(
                route.max_wire_payload_size for route in node_routes
            ),
        }
    return {"assumptions": {"mcu_pointer_bytes": 4, "work_item_bytes": 8}, "nodes": nodes}


def write_deployment(
    plan: DeploymentPlan, output: Path, authoritative_lock: Path | None = None
) -> None:
    output.mkdir(parents=True, exist_ok=True)
    lock_path = authoritative_lock or (output / "deployment.lock.yaml")
    existing = _load_existing_lock(lock_path, plan.name)
    node_ids = _allocate_ids(
        list(plan.deployment["nodes"]), existing.get("nodes", {}), 1, 255
    )
    route_ids = _allocate_ids(
        [route.name for route in plan.routes], existing.get("routes", {}), 8, 511
    )

    lock = {
        "api_version": "xrobot.io/v1alpha1",
        "kind": "DeploymentLock",
        "metadata": {"deployment": plan.name},
        "deployment_hash": plan.deployment_hash,
        "schema_hash": plan.schema_hash,
        "protocol_version": 1,
        "nodes": node_ids,
        "routes": route_ids,
        "types": dict(sorted(plan.type_hashes.items())),
        "backends": {"xrobot-can": "1"},
    }
    lock_content = _yaml(lock)
    _write_if_changed(lock_path, lock_content)
    if lock_path != output / "deployment.lock.yaml":
        _write_if_changed(output / "deployment.lock.yaml", lock_content)

    for directory in (output / "nodes", output / "reports"):
        if directory.exists():
            shutil.rmtree(directory)

    resolved = {
        "api_version": "xrobot.io/v1alpha1",
        "kind": "ResolvedDeployment",
        "metadata": {"name": plan.name},
        "deployment_hash": plan.deployment_hash,
        "schema_hash": plan.schema_hash,
        "nodes": {
            name: {
                "id": node_ids[name],
                **plan.deployment["nodes"][name],
            }
            for name in sorted(plan.deployment["nodes"])
        },
        "routes": [
            _route_document(route, route_ids[route.name]) for route in plan.routes
        ],
    }
    _write_if_changed(output / "deployment.resolved.yaml", _yaml(resolved))

    module_graph = {
        "instances": [
            {
                "name": item.name,
                "package": item.package,
                "module": item.module,
                "node": item.node,
                "ports": item.config.get("ports", {}),
            }
            for item in plan.instances
        ]
    }
    routes_report = {
        "routes": [
            _route_document(route, route_ids[route.name]) for route in plan.routes
        ]
    }
    budget_report = {
        "links": {
            budget.name: {
                "bitrate_bps": budget.bitrate_bps,
                "reserved_utilization": round(budget.reserved_utilization, 9),
                "route_utilization": round(budget.route_utilization, 9),
                "total_utilization": round(budget.total_utilization, 9),
                "utilization_limit": round(budget.utilization_limit, 9),
                "within_budget": budget.within_budget,
            }
            for budget in plan.link_budgets
        }
    }
    _write_if_changed(output / "reports/module_graph.json", _json(module_graph))
    _write_if_changed(output / "reports/routes.json", _json(routes_report))
    _write_if_changed(output / "reports/link_budget.yaml", _yaml(budget_report))
    _write_if_changed(output / "reports/executors.yaml", _yaml(_executor_report(plan)))
    _write_if_changed(output / "reports/memory.yaml", _yaml(_memory_report(plan)))

    for node_name, node_id in node_ids.items():
        node_dir = output / "nodes" / node_name
        _write_if_changed(
            node_dir / "node_config.hpp",
            _node_header(plan, node_name, node_id, route_ids),
        )
        _write_if_changed(node_dir / "generated_main.cpp", _node_main(node_name))
