"""Public interface-schema compiler entry point."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml

from xrobot_tools import __version__
from xrobot_tools.cpp_codegen import record_wire_sizes, render_header
from xrobot_tools.interface_model import (
    InterfaceError,
    InterfaceModel,
    load_interface_model,
)

__all__ = ["GenerationResult", "InterfaceError", "generate_interfaces"]


@dataclass(frozen=True)
class GenerationResult:
    interface_count: int
    record_count: int
    deployment_schema_hash: str
    header: Path
    lock: Path


def _write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def _schema_lock(model: InterfaceModel) -> str:
    sizes = record_wire_sizes(model)
    document = {
        "api_version": "xrobot.io/schema/v1alpha1",
        "kind": "SchemaLock",
        "metadata": {
            "generator": "xrobot-tools",
            "generator_version": __version__,
        },
        "deployment_schema_hash": model.deployment_schema_hash,
        "interfaces": [
            {
                "name": interface.full_name,
                "kind": interface.kind,
                "source": interface.source,
                "source_sha256": interface.source_sha256,
                "schema_hash": interface.schema_hash,
                "records": [
                    {
                        "name": record.full_name,
                        "schema_hash": record.schema_hash,
                        "max_serialized_size": sizes[record.full_name],
                    }
                    for record in interface.records
                ],
            }
            for interface in model.interfaces
        ],
    }
    return yaml.safe_dump(
        document,
        sort_keys=False,
        allow_unicode=False,
        default_flow_style=False,
    )


GENERATED_CMAKE = """\
# Generated by xrctl. Do not edit.
add_library(robot_msgs INTERFACE)
add_library(robot::msgs ALIAS robot_msgs)
target_include_directories(robot_msgs INTERFACE
  ${CMAKE_CURRENT_LIST_DIR}/include
)
target_link_libraries(robot_msgs INTERFACE xrobot::runtime)
target_compile_features(robot_msgs INTERFACE cxx_std_20)
"""


def generate_interfaces(
    schema_root: str | Path, output_dir: str | Path
) -> GenerationResult:
    model = load_interface_model(schema_root)
    output = Path(output_dir)
    header = output / "include" / "robot_msgs" / "robot_msgs.hpp"
    lock = output / "schema.lock.yaml"
    _write_if_changed(header, render_header(model))
    _write_if_changed(lock, _schema_lock(model))
    _write_if_changed(output / "CMakeLists.txt", GENERATED_CMAKE)
    return GenerationResult(
        interface_count=len(model.interfaces),
        record_count=len(model.records),
        deployment_schema_hash=model.deployment_schema_hash,
        header=header,
        lock=lock,
    )
