api_version: aster.dev/v1alpha2
kind: Package
metadata:
  name: clock
  version: 0.1.0
  license: Apache-2.0
spec:
  build:
    system: zephyr
    target: hardware_clock
  exports:
    modules: [clock-provider.module.yaml]
    protos: [../../proto/clock.proto]
  protobuf:
    bounds: ../../proto/bounds.yaml
    includes: [../../proto]
  dependencies: {}
