api_version: xrobot.io/v1alpha1
kind: Package

metadata:
  name: xrobot-transports
  version: 0.1.0-dev
  license: Apache-2.0

spec:
  build:
    system: cmake
  exports:
    libraries:
      - name: xrobot::transports
        portable: false
  dependencies:
    - xrobot-runtime
