api_version: aster.dev/v1alpha2
kind: Application
metadata:
  name: linux-local
spec:
  instances:
    source:
      module: demo/state-source
    sink:
      module: demo/state-sink
  connections:
    - from: source.state
      to: sink.state
      qos: reliable
      max_rate_hz: 20
      max_size: 40
  domains:
    - name: main
      time: monotonic
